use_frameworks!

platform :ios, '10.0'

target 'AmplifyUILivenessWrapper_Example' do
  pod 'AmplifyUILivenessWrapper', :path => '../'

  target 'AmplifyUILivenessWrapper_Tests' do
    inherit! :search_paths

    
  end
end
